# Generated by Django 6.0.2 on 2026-02-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_avatar_alter_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='favorito',
            field=models.BooleanField(default=False),
        ),
    ]
